### ISSUE TITLE
is_local_paid should not be required

### ISSUE THREAD

**Issue by ryan-gyger** [donnell74/Org.nized-API#1]
{
"error": "E_VALIDATION",
"status": 400,
"summary": "1 attribute is invalid",
"model": "Person",
"invalidAttributes": {
"is_local_paid": [
{
"rule": "in",
"message": "\"in\" validation rule failed for input: 'false'"
}
]
}
}

**Comment by donnell74** [comment]
this is because the default for is_local_paid is not in enum
